### ISSUE TITLE
valve function, number, and digital pin mapping

### ISSUE THREAD

**Issue by dpk9** [Wyss/SLuRP#10]
branch: [antibody-staining](/wyss/slurp/trees/antibody-staining)

What is the mapping for the valves to digital pins?  Attached is the layout:  

![image](https://user-images.githubusercontent.com/1790437/59517609-eda61f00-8e91-11e9-9b3a-eca34170d665.png)

P1, P2, P3 are the pumping valves. ResA-ResE are the reservoirs, Lock/Unlock Chip is the vacuum chuck valve.  

Ignore Open/Close all.  You can answer in the comments below.

**Comment by cngpit2** [comment]
P1 = D32; P2 = D34; P3 = D36;

Lock Chip is D28

resA = D30; resE = D26; resB = D24; resD = D22

I'm having issues with resC, but I will send it out to you today

**Comment by cngpit2** [comment]
resC = D40

**Comment by dpk9** [comment]
resolved

**Comment by cngpit2** [comment]
Actually, resC = D38

**Comment by dpk9** [comment]
You can change this easily, it's in /slurpy/config/ValveGridPos.yaml

**Comment by cngpit2** [comment]
Right, but after I changed it on the yaml file, I can't switch back to the master branch, unless I commit the change first on the AS branch?

**Comment by dpk9** [comment]
You should commit it. The wrong pin is committed currently so you want to
overwrite it with the correct one. Commit it, push it, and then you can
change branches freely.

**Comment by cngpit2** [comment]
I made the changed and committed into the branch. Resolved
