### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by cngpit2** [Wyss/SLuRP#12]
After duplicating multiple steps, I get the following error:
AttributeError: 'NoneType' object has no attribute 'clone'

**Comment by dpk9** [comment]
Seems to be fixed by updating pyqt5 module?

**Comment by cngpit2** [comment]
When clicking on Load protocol... from menu bar: 
AttributeError: 'View' object has no attribute 'LoadProtocolButtonClickedHandler'

**Comment by cngpit2** [comment]
I'm attaching a zip file with the protocol because yaml files are not supported.

[PulseDosingStudy.zip](https://github.com/Wyss/SLuRP/files/3315208/PulseDosingStudy.zip)
